force-app/main/default/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuestionnaireSavedAnswer__c/QuestionnaireSavedAnswer__c.object-meta.xml
<CustomObject>
    <label>QuestionnaireSavedAnswer</label>
    <nameField>
        <label>QuestionnaireSavedAnswer Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuestionnaireSavedAnswer__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>QuestionnaireSavedAnswer</relationshipLabel>
    <relationshipName>QuestionnaireSavedAnswer</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuestionnaireResultController.cls
public with sharing class QuestionnaireResultController {
    public Questionnaire__c questionnaireToShow {get; set;}
    public List<QuestionnaireSavedAnswer__c> savedAnswerList {get; set;}
    public String questionnaireId {get; set;}
    public String customerId {get; set;}
    public List<System.SelectOption> questionnaireChoices {get; set;}

    public QuestionnaireResultController() {
        questionnaireId = apexpages.currentpage().getparameters().get('questionnaireId');
        customerId = apexpages.currentpage().getparameters().get('customerId');
        if (questionnaireId != null) {
            questionnaireToShow = QuestionnaireUtility.getQuestionnaireById(questionnaireId);
            savedAnswerList = QuestionnaireUtility.retrieveSavedAnswer(questionnaireId);
        } else {
            questionnaireChoices = QuestionnaireUtility.generateAllQuestionnaireSelectOption();
        }
    }

    public Pagereference showQuestionnaire() {
        return QuestionnaireUtility.redirectSamePageWithQuestionnaireId('/apex/QuestionnaireResult', questionnaireId);
    }
}